### ISSUE TITLE
Data.Rewriting?

### ISSUE THREAD

**Issue by jwaldmann** [fabeulous/trsprop#1]
Hi. 

Can you publish Data.Rewriting? 

Then I can deprecate https://hackage.haskell.org/package/tpdb (or we could merge)

**Comment by fabeulous** [comment]
Hi.
This tool is only a tiny layer on top of http://hackage.haskell.org/package/term-rewriting, which exports all the `Data.Rewriting` types and functions. So unfortunately there is nothing for me to publish.

**Comment by jwaldmann** [comment]
oh, good, I was not aware of that.
